### ISSUE TITLE
Visual bug in landscape mode and fingerprint scanner problem

### ISSUE THREAD

**Issue by ghost** [vayu-evergarden/bug_tracker_lavender#16] opened 2020-07-07 10:48 UTC
Rom Name : Pixel Experience Plus
Build Date : 06.06.2020
Rooted or Unrooted : Rooted with Magisk
Custom Kernel or Stock Kernel : Stock
Steps to reproduce the problem : 1. When landscape in Chrome Browser the status bar have bugs: https://imgur.com/a/qSCvLFJ
2. Every time when i unlock the phone with the fingerprint i need to press on the fingerprint scanner twice to unlock my phone. Sometimes when i press fingerprint scanner and i press it for 2 sec will unlock my phone but only sometimes. In miui when i press one time on the fingerprint scanner the phone is unlocking immediately.
3. When I am charging my phone, it starts overheating: https://imgur.com/a/Yb8EboZ 
I never use my phone when I charge it and the temperature when I was charging my phone was 18 degrees celsius. In miui the phone was not overheating. I am using the original charger and cable, no fastcharging. The last time I let the phone charge for 30 minutes the tempeature was 50 degrees celsius.
4.I have some suggestions for pixel experience plus:
 a. put in top right corner the battery procent for a better design. Here in the top right corner I mean: https://imgur.com/a/lKTYeqG
b.make a toggle to disabe and enable the vibration when turn off the phone. 
c. Make a toggle to disable google news from home launcher.
d. Take the audio files from Miui rom and put it in this rom I think will be an improvement in audio quality.
Any magisk modules ? : L1 patch, Dolby Atmos and Audio Modification Library
Logcat : https://drive.google.com/file/d/10rv4oP9l6wXkABls21VGlWNeDabh1hUP/view?usp=drivesdk 
Thank you for taking the time to read these suggestions and bugs.
 Regards,
 Radu

**Comment by piyushdahiya1218** [comment] 2020-07-17 13:26
I'm also facing the problem related to status bar describe in point 1. Just wanted to point out that the bug is also present in other apps like WhatsApp and YouTube.
https://postimg.cc/0MRRnbLx
https://postimg.cc/4HXCCjfS

**Comment by etahamad** [comment] 2020-08-20 19:01
If you have time, contact me on telegram @etahamad to fix the issues one by one.

**Comment by etahamad** [comment] 2020-08-20 19:06
1. chrome issue
It's not a bug, all apps have that with 3-button navigation bar.
solution: it's not a bug so, you can use navigation bar pill (android 10 default).

**Comment by etahamad** [comment] 2020-08-20 19:08
2. fingerprint scanner
As i read, Fingerprint scanner have delay, right? i think it's due to CPU DeepSleep, really i don't know, it's better to provide logcat while locking / unlocking your device.

**Comment by etahamad** [comment] 2020-08-20 19:11
3.battery overheating while charging,
Man, it's normal to overheat while charging, it reaches 47°C.
Solution: when battery reaches 90% while charging, it slows down the charger speed, by that your battery will cool down, by reaching 96% it will reach the normal temp.

**Comment by etahamad** [comment] 2020-08-20 19:21
4. A. I think we already have that?

4. B. AOSP have this feature by default, just go to settings/system/gestures/prevent ringing 
![Screenshot_20200820-211403877](https://user-images.githubusercontent.com/53538887/90815023-4ee54000-e32a-11ea-9274-758c55fda750.jpg)

4. C. Go to Google / settings / disable Discover as screenshot.
![Screenshot_20200820-211648822](https://user-images.githubusercontent.com/53538887/90815487-15f99b00-e32b-11ea-8c3e-a7636fa70646.jpg)


4. D. We already have Mi Sound Dirac, go to settings / audio / last one as screenshot.
![Screenshot_20200820-211948252](https://user-images.githubusercontent.com/53538887/90815511-1bef7c00-e32b-11ea-85ba-4eb6088daa0b.jpg)

**Comment by ghost** [comment] 2020-08-20 19:45
> 1. chrome issue
>    It's not a bug, all apps have that with 3-button navigation bar.
>    solution: it's not a bug so, you can use navigation bar pill (android 10 default).

I mean the clock is on the navigation bar and you mister say that is not a bug?

**Comment by ghost** [comment] 2020-08-20 19:52
> 3.battery overheating while charging,
> Man, it's normal to overheat while charging, it reaches 40°C.
> Solution: when battery reaches 90% while charging, it slows down the charger speed, by that your battery will cool down, by reaching 96% it will reach the normal temp.

The problem is not if the cpu reach 40°C, the problem is that the cpu is reaching 51°C, as I shown in the photo the cpu reached 47°C because I not waited too much. Miui reaches maximum 45°C as an exemple.

**Comment by etahamad** [comment] 2020-08-20 20:03
> > 1. chrome issue
> >    It's not a bug, all apps have that with 3-button navigation bar.
> >    solution: it's not a bug so, you can use navigation bar pill (android 10 default).
> 
> I mean the clock is on the navigation bar and you mister say that is not a bug?

No, It's not a bug, run any app and check in landscape

**Comment by etahamad** [comment] 2020-08-20 20:05
> > 3.battery overheating while charging,
> > Man, it's normal to overheat while charging, it reaches 40°C.
> > Solution: when battery reaches 90% while charging, it slows down the charger speed, by that your battery will cool down, by reaching 96% it will reach the normal temp.
> 
> The problem is not if the cpu reach 40°C, the problem is that the cpu is reaching 51°C, as I shown in the photo the cpu reached 47°C because I not waited too much. Miui reaches maximum 45°C as an exemple.

Stock kernel is overheating a little by default i know, maybe it's heating over the regular temp so it's overheating, my advice is to install Predator-Stormbreaker Kernel, i'm using it as many people + roms as stock kernel

**Comment by ghost** [comment] 2020-08-20 20:10
> 1. fingerprint scanner
>    As i read, Fingerprint scanner have delay, right? i think it's due to CPU DeepSleep, really i don't know, it's better to provide logcat while locking / unlocking your device.

No, fingerprint scanner doesn t have delay, as I said if I press once and quick the phone will not unlock, if i press on the fingerprint scanner twice and quick the phone will unlock. As an exemple in Miui if i press once and quick will unlock the phone. I can t provide any further logcat because I don t use this rom anymore but I wanted to help other people who use this rom. The logcat from this post can ne downloaded now.

**Comment by ghost** [comment] 2020-08-20 20:18
> 1. A. I think we already have that?
> 2. B. AOSP have this feature by default, just go to settings/system/gestures/prevent ringing
>    ![Screenshot_20200820-211403877](https://user-images.githubusercontent.com/53538887/90815023-4ee54000-e32a-11ea-9274-758c55fda75
> 4. D. We already have Mi Sound Dirac, go to settings / audio / last one as screenshot.
>    ![Screenshot_20200820-211948252](https://user-images.githubusercontent.com/53538887/90815511-1bef7c00-e32b-11ea-85ba-4eb6088daa0b.jpg)

It isn t what I meant, any rom have an audio code right? Well the audio from this good can be improved by taking the audio code from Miui original rom and add to this rom.

**Comment by piyushdahiya1218** [comment] 2020-08-20 21:28
> > > 1. chrome issue
> > >    It's not a bug, all apps have that with 3-button navigation bar.
> > >    solution: it's not a bug so, you can use navigation bar pill (android 10 default).
> > 
> > 
> > I mean the clock is on the navigation bar and you mister say that is not a bug?
> 
> No, It's not a bug, run any app and check in landscape

Can you take a look at these screenshots.  [https://imgur.com/a/qSCvLFJ](url)
The time on the left and battery percentage on the right are clearly hidden because of the navigation bar(no matter which one you use). Even if it is not a bug dont you think it should be fixed

**Closed as completed** 2020-11-29 08:10 UTC
